package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = '01FastTests'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("01FastTests")) {
    expectSteps {
    }
    steps {
        insert(0) {
            script {
                name = "Browser Tests"
                id = "RUNNER_7"
                enabled = false
                scriptContent = "npm test -- --single-run --browsers PhantomJS --colors false --reporters teamcity"
            }
        }
    }
}
