package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.buildSteps.powerShell
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = '01FastTests'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("01FastTests")) {
    expectSteps {
    }
    steps {
        insert(0) {
            powerShell {
                id = "RUNNER_9"
                enabled = false
                scriptMode = script {
                    content = """
                        ${'$'}name = get-service | where {${'$'}_.Name -like "*BuildAgent*"}
                        Restart-Service ${'$'}name
                    """.trimIndent()
                }
            }
        }
    }
}
