package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = '02Chrome'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("02Chrome")) {
    expectSteps {
    }
    steps {
        check(stepsOrder == arrayListOf<String>()) {
            "Unexpected build steps order: $stepsOrder"
        }
        stepsOrder = arrayListOf("RUNNER_13", "RUNNER_6", "RUNNER_7")
    }
}
